### ISSUE TITLE
request: add dev dependencies

### ISSUE THREAD

**Issue by Swiizyy** [sapphiredev/cli#218]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Add sapphire and discord modules to the dev dependencies.

### Desired solution

This modification would bring auto-completion at the time of the writing or the modification of the examples what will avoid many problem of typing that one can make without this one.

### Alternatives considered

An alternative solution is that each contributor adds them himself but it's honestly not that great to add them to have the auto-completion directly.

**Comment by favna** [comment]
Added. It should be noted however that type checking the `.sapphire` files is impossible because they do not end in one of `.ts`, `.js`, `.tsx`, or `.jsx` which means TypeScript cannot parse them. Not to mention the config header which it would break on.
